project.name=lab4
project.version=1.0.0
main.class=com.example.lab3.App

source.encoding=UTF-8
javac.release=17

src.main.dir=src/main/java
src.resources.dir=src/main/resources
build.dir=ant-build
classes.dir=${build.dir}/classes
lib.dir=${build.dir}/lib
manifest.template=ant/MANIFEST.MF.template
manifest.file=${build.dir}/MANIFEST.MF

dist.dir=dist
dist.lib.dir=${dist.dir}/lib
dist.jar.file=${dist.dir}/${project.name}-${project.version}.jar
dist.root.war.file=${dist.dir}/ROOT.war

native.src.dir=${src.resources.dir}/i18n
native.dest.dir=${build.dir}/native2ascii
native.encoding=UTF-8
native.file.default=messages.properties
native.file.ru=messages_ru.properties

javadoc.dir=${build.dir}/javadoc
javadoc.jar.file=${dist.dir}/${project.name}-${project.version}-javadoc.jar
checksums.dir=${dist.dir}/checksums
doc.archive.file=${dist.dir}/${project.name}-${project.version}-docs.zip
checksum.md5.algorithm=MD5
checksum.sha1.algorithm=SHA-1

history.script=scripts/history.sh
history.report.dir=${dist.dir}
history.report.file=${history.report.dir}/history-report.txt
history.shell.bin=/bin/bash

qodana.bin=qodana
qodana.config.file=qodana.yaml
qodana.linter=qodana-jvm-community
qodana.within.docker=false
qodana.results.dir=${dist.dir}/qodana/results
qodana.report.dir=${dist.dir}/qodana/report
qodana.extra.args=--print-problems

env.java.home=${java.home}
env.jvm.args=-Duser.language=ru -Duser.country=RU

scp.enabled=true
scp.bin=scp
scp.ssh.bin=ssh
scp.user=s465826
scp.host=se.ifmo.ru
scp.remote.dir=~/wildfly/standalone/deployments
scp.remote.war.name=ROOT.war
scp.identity.file=${user.home}/.ssh/id_ed25519
scp.redeploy.touch.enabled=true
scp.redeploy.command=touch ${scp.remote.dir}/${scp.remote.war.name}.dodeploy
scp.port=2222

report.junit.source.dir=target/surefire-reports
report.junit.includes=TEST-*.xml
report.copy.dir=${dist.dir}/reports
report.git.commit.enabled=false
report.git.repo=${basedir}
report.git.pathspec=target/surefire-reports
report.git.commit.message=Add junit XML report
git.bin=git

maven.bin=mvn
maven.resolve.compile.args=-q -DskipTests dependency:copy-dependencies -DincludeScope=compile -DoutputDirectory=${lib.dir}
maven.resolve.runtime.args=-q -DskipTests dependency:copy-dependencies -DincludeScope=runtime -DoutputDirectory=${lib.dir}
maven.test.args=-q test
maven.package.args=-q -DskipTests package
maven.war.file=target/lab4.war
