# -*- coding: utf-8 -*-
"""/matstat/cgw/1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iw7ffOAbuK_yXn0cFm7oJ14NJ16fPDGp

# Расчётно-графическая работа №1

## 2. Вариант и выборка

### Вариант A-7

- В работе моделируется типичная ситуация: дана выборка из 200 наблюдений, и требуется сделать обоснованные выводы по данным.

- Примеры для группы A: время отклика сервиса на запрос, задержка передачи данных, время выполнения стандартной операции в системе.

- X1-X4 – разные показатели из одного прикладного контекста. Соответствие «столбец – закон» заранее не сообщается и определяется по данным.

- Единицы измерения: мс.

- Значения в CSV округлены до 2 знаков после запятой.

### Загрузка выборки

[выборка на диске](https://drive.google.com/file/d/15bxmwkK1BX3RycrMlh8KU3hGWOUaLfvJ/view?usp=drive_link)

загрузка с диска в среду выполнения `/content/data.csv`
"""

import os

if not os.path.exists('/usr/local/bin/gdown'):
    !pip install -q gdown

import gdown

file_id = '15bxmwkK1BX3RycrMlh8KU3hGWOUaLfvJ'
output_filename = 'data.csv'

try:
    gdown.download(id=file_id, output=output_filename, quiet=False)
    print(f"File '{output_filename}' downloaded successfully.")
except Exception as e:
    print(f"Error downloading file: {e}")

"""## 4. Выполнение работы

### 4.1 Первичное описание выборки (Лёша Соловьёв)

#### 1. Постройте вариационный ряд.
"""

import pandas as pd

df = pd.read_csv('data.csv')

columns = ['X1', 'X2', 'X3']

for col in columns:
    variational_series = df[col].sort_values().reset_index(drop=True)

    print(f"вариационный ряд для {col}:")
    print(variational_series.to_string())
    print("\n\n")

"""#### 2. Постройте эмпирическую функцию распределения Fn(x)."""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv('data.csv')

columns = ['X1', 'X2', 'X3']

fig, axes = plt.subplots(2, 2, figsize=(15, 12))
axes = axes.flatten()

for i, col in enumerate(columns):
    data = df[col].sort_values().reset_index(drop=True)
    n = len(data)

    x_ecdf = np.sort(data)
    y_ecdf = np.arange(1, n + 1) / n

    axes[i].step(x_ecdf, y_ecdf, where='post')
    axes[i].set_xlabel(f'значение случайной величины X ({col})')
    axes[i].set_ylabel('F_n(x)')
    axes[i].set_title(f'эмпирическая функция распределения для {col}')
    axes[i].grid(True)


if len(columns) < len(axes):
    for j in range(len(columns), len(axes)):
        fig.delaxes(axes[j])

plt.tight_layout()
plt.show()

"""#### 3. Постройте гистограмму (обоснуйте выбор числа интервалов/ширины интервала; допускаются стандартные правила, см. Приложение А). Рекомендуется построить несколько гистограмм с разными правилами и сравнить результат."""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv('data.csv')

columns = ['X1', 'X2', 'X3']

# правило Скотта
def scott_bins(data):
    n = len(data)
    if n < 2 or data.std() == 0:
        return 1 # краевые случаи
    h = 3.5 * data.std() / (n**(1/3))
    # поделили все значения на части шириной h и получили их число
    return int(np.ceil((data.max() - data.min()) / h)) if h > 0 else 1

# правило Фридмана-Диакониса
def freedman_diaconis_bins(data):
    n = len(data)
    if n < 2:
        return 1
    Q1 = data.quantile(0.25)
    Q3 = data.quantile(0.75)
    IQR = Q3 - Q1
    if IQR == 0:
        return 1 # краевой случай
    h = 2 * IQR / (n**(1/3))
    # поделили все значения на части шириной h и получили их число
    return int(np.ceil((data.max() - data.min()) / h)) if h > 0 else 1

# правило Стерджеса
def sturges_bins(data):
    n = len(data)
    # в отличие от остальных даёт сразу число
    return int(1 + np.floor(np.log2(n))) if n > 0 else 1


for col in columns:
    data = df[col]
    # к-во интервалов по разным правилам
    bins_scott = scott_bins(data)
    bins_fd = freedman_diaconis_bins(data)
    bins_sturges = sturges_bins(data)

    fig, axes = plt.subplots(1, 3, figsize=(20, 6))
    fig.suptitle(f'Гистограммы для столбца {col}', fontsize=16)

    # по Скотта
    axes[0].hist(data, bins=bins_scott, edgecolor='black', alpha=0.7)
    axes[0].set_title(f'Правило Скотта (бин: {bins_scott})')
    axes[0].set_xlabel('Значение')
    axes[0].set_ylabel('Частота')
    axes[0].grid(axis='y', alpha=0.75)

    # по Фридмана-Диакониса
    axes[1].hist(data, bins=bins_fd, edgecolor='black', alpha=0.7)
    axes[1].set_title(f'Правило Фридмана-Диакониса (бин: {bins_fd})')
    axes[1].set_xlabel('Значение')
    axes[1].set_ylabel('Частота')
    axes[1].grid(axis='y', alpha=0.75)

    #по Стерджеса
    axes[2].hist(data, bins=bins_sturges, edgecolor='black', alpha=0.7)
    axes[2].set_title(f'Правило Стерджеса (бин: {bins_sturges})')
    axes[2].set_xlabel('Значение')
    axes[2].set_ylabel('Частота')
    axes[2].grid(axis='y', alpha=0.75)

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.show()

"""#### 4. Вычислите числовые характеристики: выборочное среднее x, дисперсию (смещённую) S2, дисперсию (несмещённую) ˆσ2, стандартные отклонения S и ˆσ, медиану me и квантили (в том числе квартили).

$$\text{Выборочное среднее: } \bar{X} = \frac{1}{n} \sum_{i=1}^{n} X_i$$

$$\text{Выборочная дисперсия (смещённая): } S^2 = \frac{1}{n} \sum_{i=1}^{n} (X_i - \bar{X})^2$$
$$\text{Выборочное стандартное отклонение (смещённое): } S = \sqrt{S^2}$$

$$\text{Несмещённая выборочная дисперсия (исправленная): } \hat{\sigma}^2 = \frac{1}{n-1} \sum_{i=1}^{n} (X_i - \bar{X})^2$$
$$\text{Несмещённое выборочное стандартное отклонение (исправленное): } \hat{\sigma} = \sqrt{\hat{\sigma}^2}$$

$$\text{Медиана: } me = Q_{0.5}$$

$$\text{Квантили (перцентили): } Q_p \text{, где } p \text{ - доля наблюдений меньше или равных значению.}$$
"""

import pandas as pd
import numpy as np

df = pd.read_csv('data.csv')

columns = ['X1', 'X2', 'X3']

for col in columns:
    data = df[col]
    n = len(data)

    # Выборочное среднее
    sample_mean = data.mean()

    # Смещенная выборочная дисперсия
    biased_variance = data.var(ddof=0) # ddof=0 для смещенной дисперсии
    # Смещенное стандартное отклонение
    biased_std_dev = data.std(ddof=0) # ddof=0 для смещенного стандартного отклонения

    # Несмещенная выборочная дисперсия
    unbiased_variance = data.var(ddof=1) # ddof=1 для несмещенной дисперсии (по умолчанию в pandas)
    # Несмещенное стандартное отклонение
    unbiased_std_dev = data.std(ddof=1) # ddof=1 для несмещенного стандартного отклонения (по умолчанию в pandas)

    # Медиана
    median = data.median()

    # Квартили (25%, 50%, 75%)
    Q1 = data.quantile(0.25)
    Q2 = data.quantile(0.50) # Это та же медиана
    Q3 = data.quantile(0.75)

    # Другие квантили (например, 10% и 90%)
    percentile_10 = data.quantile(0.10)
    percentile_90 = data.quantile(0.90)

    print(f"\n--- Характеристики для столбца {col} ---")
    print(f"Выборочное среднее (X): {sample_mean:.2f}")
    print(f"Смещенная дисперсия (S^2): {biased_variance:.2f}")
    print(f"Смещенное стандартное отклонение (S): {biased_std_dev:.2f}")
    print(f"Несмещенная дисперсия (σ^2): {unbiased_variance:.2f}")
    print(f"Несмещенное стандартное отклонение (σ): {unbiased_std_dev:.2f}")
    print(f"Медиана (me): {median:.2f}")
    print(f"25-й перцентиль (Q1): {Q1:.2f}")
    print(f"50-й перцентиль (Q2/Медиана): {Q2:.2f}")
    print(f"75-й перцентиль (Q3): {Q3:.2f}")
    print(f"10-й перцентиль: {percentile_10:.2f}")
    print(f"90-й перцентиль: {percentile_90:.2f}")

"""#### 5. Коротко опишите форму распределения: симметрия/асимметрия, наличие выбросов, наличие/отсутствие естественных границ значений

Столбец X1:

- Симметрия/Асимметрия: Выборочное среднее (50.77) немного больше медианы (48.22). Это указывает на небольшую положительную асимметрию (правосторонняя), то есть распределение имеет более длинный «хвост» в сторону больших значений, но в целом ~симметрично относительно центра
- Выбросы: небольшой выброс в в области больших значений, без его учёта данные смещены к меньшим значениям СВ
- Естественные границы: Данные представляют собой время отклика, что предполагает неотрицательные значения, т.е. нижняя граница естественна: > 0, в данном случа 20 мс, а верхняя граница не имеет явных физических ограничений, но в данном случае 90 мс, кроме очень больших значений.


Столбец X2:

- Симметрия/Асимметрия: Выборочное среднее (40.97) и медиана (32.76). С учётом того, что центр гистограммы для значения СВ 90мс, то величина заметно смещена в сторону низких значений задержки
- Выбросы: по гистограммам отсутствуют
- Естественные границы: 15мс снизу и 165мс сверху

Столбец X3:

- Симметрия/Асимметрия: Выборочное среднее (41.72) очень близко к медиане (41.87). Это говорит о том, что распределение ~симметрично.
- Выбросы: Диапазон значений между 10-м (35.00) и 90-м (48.65) перцентилями значительно уже, чем у X1 и X2, а стандартные отклонения (S=5.29, σ=5.31) также меньше. Это указывает на меньший разброс данных и, вероятно, отсутствие значительных выбросов. Гистограмма подтверждает предположение
- Естественные границы: 15мс и 60мс

### 4.2 Предположение о законе распределения (Лёша Соловьёв)

Используя гистограмму, ЭФР и числовые характеристики, для каждого столбца выберите
наиболее подходящую модель из списка: Na,σ, Ua,b, Expλ,c. Дайте краткое обоснование
(2–6 предложений)

1. Столбец $X_1$ соответсвует равномерному распределению $U_{a,b}$
  - по гистрогамме, построенной по правилу Стерджеса особенно хорошо заметно, что значения случайной величины в пределах границ условно равновероятны
2. Столбец $X_2$ соответсвует экспонециальному распределению $Exp_{\lambda, c}$
  - Небольшой сдвиг $c$, связанный с нижней границей и $\lambda$, связанная с быстрым спаданием к нулю
3. Столбец $X_3$ соответсвует нормальное распределение
  - симметричное относительно $a$ с значительным скоплением значений в пределах $\sigma$

### 4.3 Оценивание параметров: метод моментов и метод максимального правдоподобия (Лёша Соловьёв) - это я пересмотрю ещё, тут нейрослоп, но значения вроде норм

#### 1. Метод моментов: приравняйте теоретические моменты EX и DX к соответствующим выборочным характеристикам и найдите оценки параметров.
"""

import pandas as pd
import numpy as np

df = pd.read_csv('data.csv')

columns = ['X1', 'X2', 'X3']

print("--- Оценки параметров методом моментов ---")

for col in columns:
    data = df[col]
    sample_mean = data.mean()
    biased_variance = data.var(ddof=0) # Используем смещенную дисперсию для метода моментов

    print(f"\nДля столбца {col}:")

    if col == 'X1': # Равномерное распределение U(a, b)
        # E[X] = (a + b) / 2 = sample_mean
        # Var[X] = (b - a)^2 / 12 = biased_variance
        # Решаем систему уравнений:
        # a + b = 2 * sample_mean
        # (b - a)^2 = 12 * biased_variance
        if biased_variance < 0: # Это не должно произойти с реальными данными
            print("  Ошибка: Выборочная дисперсия должна быть неотрицательной.")
            continue

        sqrt_12_var = np.sqrt(12 * biased_variance)
        param_a = (2 * sample_mean - sqrt_12_var) / 2
        param_b = (2 * sample_mean + sqrt_12_var) / 2

        print(f"  Предполагаемое распределение: Равномерное U(a, b)")
        print(f"  Оценка a: {param_a:.2f}")
        print(f"  Оценка b: {param_b:.2f}")
        if param_a > data.min() or param_b < data.max():
             print(f"  Внимание: Оценочный интервал U([{param_a:.2f}, {param_b:.2f}]) не полностью охватывает наблюдаемые данные [{data.min():.2f}, {data.max():.2f}]. Это может указывать на несоответствие модели.")

    elif col == 'X2': # Экспоненциальное распределение Exp(lambda, c)
        # E[X] = c + 1/lambda = sample_mean
        # Var[X] = 1/lambda^2 = biased_variance
        # Решаем систему уравнений:
        # lambda = 1 / sqrt(biased_variance)
        # c = sample_mean - 1/lambda
        if biased_variance <= 0:
            print("  Ошибка: Выборочная дисперсия должна быть положительной для экспоненциального распределения.")
            continue

        param_lambda = 1 / np.sqrt(biased_variance)
        param_c = sample_mean - (1 / param_lambda)

        print(f"  Предполагаемое распределение: Сдвинутое экспоненциальное Exp(lambda, c)")
        print(f"  Оценка lambda: {param_lambda:.2f}")
        print(f"  Оценка c: {param_c:.2f}")
        if param_c > data.min():
            print(f"  Внимание: Оценка параметра с ({param_c:.2f}) больше минимального значения в выборке ({data.min():.2f}). Это может указывать на несоответствие модели или некорректность предположения о параметре с.")

    elif col == 'X3': # Нормальное распределение N(a, sigma)
        # E[X] = a = sample_mean
        # Var[X] = sigma^2 = biased_variance
        # Решаем:
        # a = sample_mean
        # sigma = sqrt(biased_variance)
        if biased_variance < 0:
            print("  Ошибка: Выборочная дисперсия должна быть неотрицательной.")
            continue

        param_a = sample_mean
        param_sigma = np.sqrt(biased_variance)

        print(f"  Предполагаемое распределение: Нормальное N(a, sigma)")
        print(f"  Оценка a (мат. ожидание): {param_a:.2f}")
        print(f"  Оценка sigma (станд. отклонение): {param_sigma:.2f}")
    else:
        print(f"  Распределение для столбца {col} не было определено в предыдущих шагах.")

"""#### 2. Метод максимального правдоподобия: выпишите функцию правдоподобия (или логарифм правдоподобия) и найдите оценки, максимизирующие её."""

import pandas as pd
import numpy as np

df = pd.read_csv('data.csv')

columns = ['X1', 'X2', 'X3']

print("--- Оценки параметров методом максимального правдоподобия ---")

for col in columns:
    data = df[col]
    n = len(data)

    print(f"\nДля столбца {col}:")

    if col == 'X1': # Равномерное распределение U(a, b)
        # MLE оценки для равномерного распределения: a_hat = min(X), b_hat = max(X)
        mle_a = data.min()
        mle_b = data.max()

        print(f"  Предполагаемое распределение: Равномерное U(a, b)")
        print(f"  Оценка a (MLE): {mle_a:.2f}")
        print(f"  Оценка b (MLE): {mle_b:.2f}")

    elif col == 'X2': # Сдвинутое экспоненциальное распределение Exp(lambda, c)
        # MLE оценки для сдвинутого экспоненциального распределения:
        # c_hat = min(X)
        # lambda_hat = 1 / (mean(X) - c_hat)
        mle_c = data.min()
        if data.mean() - mle_c <= 0:
            print("  Ошибка: Среднее значение меньше или равно c_hat. Невозможно вычислить lambda.")
            mle_lambda = np.nan
        else:
            mle_lambda = 1 / (data.mean() - mle_c)

        print(f"  Предполагаемое распределение: Сдвинутое экспоненциальное Exp(lambda, c)")
        print(f"  Оценка c (MLE): {mle_c:.2f}")
        print(f"  Оценка lambda (MLE): {mle_lambda:.2f}")

    elif col == 'X3': # Нормальное распределение N(a, sigma)
        # MLE оценки для нормального распределения: mu_hat = mean(X), sigma_hat^2 = biased_variance
        mle_a = data.mean()
        mle_sigma = data.std(ddof=0) # Использование смещенного стандартного отклонения (или sqrt(biased_variance))

        print(f"  Предполагаемое распределение: Нормальное N(a, sigma)")
        print(f"  Оценка a (мат. ожидание) (MLE): {mle_a:.2f}")
        print(f"  Оценка sigma (станд. отклонение) (MLE): {mle_sigma:.2f}")

    else:
        print(f"  Распределение для столбца {col} не было определено в предыдущих шагах.")

"""#### 3. Сравнение: сравните численно оценки двух методов и прокомментируйте различия (если они есть).

##### Столбец X1 (Равномерное распределение U(a, b))

*   **Метод моментов (ММ):**
    *   Оценка `a`: 17.97
    *   Оценка `b`: 83.58
    *   *Примечание:* Оценочный интервал `U([17.97, 83.58])` не полностью охватывает наблюдаемые данные `[20.98, 84.11]`. Это может указывать на несоответствие модели.
*   **Метод максимального правдоподобия (ММП):**
    *   Оценка `a` (MLE): 20.98
    *   Оценка `b` (MLE): 84.11

**Комментарий:** Для равномерного распределения метод максимального правдоподобия дает оценки, которые точно соответствуют минимальному и максимальному значениям выборки. Метод моментов, основываясь на среднем и дисперсии, дает более сглаженные оценки, которые не обязательно совпадают с крайними точками выборки. В данном случае оценки ММП более точно отражают наблюдаемый диапазон данных, что логично для равномерного распределения, где крайние точки являются важными параметрами.

##### Столбец X2 (Сдвинутое экспоненциальное распределение Exp(lambda, c))

*   **Метод моментов (ММ):**
    *   Оценка `lambda`: 0.04
    *   Оценка `c`: 15.66
*   **Метод максимального правдоподобия (ММП):**
    *   Оценка `c` (MLE): 16.82
    *   Оценка `lambda` (MLE): 0.04

**Комментарий:** Оценки `lambda` для обоих методов очень близки (0.04). Однако оценка сдвига `c` немного отличается: 15.66 для ММ и 16.82 для ММП. Метод максимального правдоподобия для сдвинутого экспоненциального распределения естественным образом оценивает `c` как минимальное значение в выборке, что является эффективной оценкой. Расхождение между `c` (ММ) и `data.min()` для ММ может быть связано с тем, что ММ не использует напрямую экстремальные значения, а опирается на моменты.

##### Столбец X3 (Нормальное распределение N(a, sigma))

*   **Метод моментов (ММ):**
    *   Оценка `a` (мат. ожидание): 41.72
    *   Оценка `sigma` (станд. отклонение): 5.29
*   **Метод максимального правдоподобия (ММП):**
    *   Оценка `a` (мат. ожидание) (MLE): 41.72
    *   Оценка `sigma` (станд. отклонение) (MLE): 5.29

**Комментарий:** Для нормального распределения оценки параметров (математического ожидания `a` и стандартного отклонения `sigma`) полученные обоими методами, практически идентичны. Это ожидаемо, так как для нормального распределения выборочное среднее является несмещенной и состоятельной оценкой математического ожидания, а выборочная дисперсия (соответствующим образом скорректированная) — несмещенной и состоятельной оценкой дисперсии, и эти оценки совпадают с оценками максимального правдоподобия.

### 4.4
"""



"""### 4.5"""



"""### 4.6"""



"""### 4.7 Вывод

## 6. Дополнительное задание

### 1.1 Эмпирическая функция распределения для X4
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv('data.csv') # Load df here
col = 'X4' # Define col here
data_x4 = df[col] # Define data_x4 here

data_sorted = data_x4.sort_values().reset_index(drop=True)
n = len(data_sorted)

x_ecdf = np.sort(data_sorted)
y_ecdf = np.arange(1, n + 1) / n

plt.figure(figsize=(10, 6))
plt.step(x_ecdf, y_ecdf, where='post')
plt.xlabel(f'Значение случайной величины ({col})')
plt.ylabel('F_n(x)')
plt.title(f'Эмпирическая функция распределения для {col}')
plt.grid(True)
plt.show()

"""### 1.1 Гистограммы для X4"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import warnings
warnings.filterwarnings('ignore') # Filter out KMeans warnings about inertia

df = pd.read_csv('data.csv')
col = 'X4'
data_x4 = df[col]

# Правила для определения числа интервалов
def scott_bins(data):
    n = len(data)
    if n < 2 or data.std() == 0: return 1
    h = 3.5 * data.std() / (n**(1/3))
    return int(np.ceil((data.max() - data.min()) / h)) if h > 0 else 1

def freedman_diaconis_bins(data):
    n = len(data)
    if n < 2: return 1
    Q1 = data.quantile(0.25)
    Q3 = data.quantile(0.75)
    IQR = Q3 - Q1
    if IQR == 0: return 1
    h = 2 * IQR / (n**(1/3))
    return int(np.ceil((data.max() - data.min()) / h)) if h > 0 else 1

def sturges_bins(data):
    n = len(data)
    return int(1 + np.floor(np.log2(n))) if n > 0 else 1

bins_scott = scott_bins(data_x4)
bins_fd = freedman_diaconis_bins(data_x4)
bins_sturges = sturges_bins(data_x4)

fig, axes = plt.subplots(1, 3, figsize=(20, 6))
fig.suptitle(f'Гистограммы для столбца {col}', fontsize=16)

axes[0].hist(data_x4, bins=bins_scott, edgecolor='black', alpha=0.7)
axes[0].set_title(f'Правило Скотта (бин: {bins_scott})')
axes[0].set_xlabel('Значение')
axes[0].set_ylabel('Частота')
axes[0].grid(axis='y', alpha=0.75)

axes[1].hist(data_x4, bins=bins_fd, edgecolor='black', alpha=0.7)
axes[1].set_title(f'Правило Фридмана-Диакониса (бин: {bins_fd})')
axes[1].set_xlabel('Значение')
axes[1].set_ylabel('Частота')
axes[1].grid(axis='y', alpha=0.75)

axes[2].hist(data_x4, bins=bins_sturges, edgecolor='black', alpha=0.7)
axes[2].set_title(f'Правило Стерджеса (бин: {bins_sturges})')
axes[2].set_xlabel('Значение')
axes[2].set_ylabel('Частота')
axes[2].grid(axis='y', alpha=0.75)

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

"""#### 1.3 Описание формы распределения X4 и признаки неоднородности

На основе гистограмм видно, что распределение для X4 является бимодальным, то есть имеет два ярко выраженных пика. Это указывает на наличие двух различных групп или режимов в данных, а не на однородную выборку. Эмпирическая функция распределения (ЭФР) также подтверждает это, показывая два участка с более крутым подъемом, соответствующие областям высокой плотности значений.

#### 2. Разделите выборку на два кластера и сравните характеристики подвыборок
"""

k_means = KMeans(n_clusters=2, random_state=42, n_init='auto')
df['cluster'] = k_means.fit_predict(data_x4.to_frame())

cluster_0 = df[df['cluster'] == 0][col]
cluster_1 = df[df['cluster'] == 1][col]

print("Характеристики Кластера 0:")
print(cluster_0.describe())
print("\nХарактеристики Кластера 1:")
print(cluster_1.describe())

print("\nСравнение характеристик кластеров:")
print(f"Среднее значение Кластера 0: {cluster_0.mean():.2f}")
print(f"Среднее значение Кластера 1: {cluster_1.mean():.2f}")
print(f"Медиана Кластера 0: {cluster_0.median():.2f}")
print(f"Медиана Кластера 1: {cluster_1.median():.2f}")
print(f"Стандартное отклонение Кластера 0: {cluster_0.std():.2f}")
print(f"Стандартное отклонение Кластера 1: {cluster_1.std():.2f}")

plt.figure(figsize=(10, 6))
plt.hist(cluster_0, bins=bins_fd, alpha=0.7, label='Кластер 0', color='skyblue', edgecolor='black')
plt.hist(cluster_1, bins=bins_fd, alpha=0.7, label='Кластер 1', color='lightcoral', edgecolor='black')
plt.title(f'Гистограммы кластеров для столбца {col}')
plt.xlabel('Значение')
plt.ylabel('Частота')
plt.legend()
plt.grid(axis='y', alpha=0.75)
plt.show()

"""#### 3. Объясните, почему «общее среднее» может плохо описывать смесь двух режимов.

Общее среднее (математическое ожидание) для бимодального распределения может быть плохим описателем, потому что оно представляет собой 'среднее' значение, которое может не соответствовать ни одному из фактических 'центров' двух мод. Если распределение имеет два пика, то среднее может оказаться между этими пиками, в области с низкой плотностью вероятности, где мало реальных наблюдений. В таком случае, оно не будет репрезентативно для типичных значений ни одной из подгрупп, вводя в заблуждение относительно истинной структуры данных. Вместо одного общего среднего, более информативным будет рассмотрение средних значений для каждой моды/кластера отдельно, что позволяет понять характеристики каждой отдельной группы.
"""